#!/usr/bin/bash

export GITHUB_ACTOR=franzgruberleitner-htl
export GITHUB_TOKEN=ZnJhbnpncnViZXJsZWl0bmVyLWh0bDpnaHBfOXdGSVQ3ZnBKNXpGeHpwOWFWd0xYNnFnUjdBOUlvM2dTYWRW
export GITHUB_REPOSITORY=franzgruberleitner-htl

